### ISSUE TITLE
When setting '--classical' to 'True', an error occurred.

### ISSUE THREAD

**Issue by glin2022** [YemingMeng/ResMPS#1]
您好，当我想要测试regular MPS性能时发生了错误：

在已有代码的基础上，我仅修改了以下的一行代码，训练结果崩溃了。
```
# parser.add_argument('--classical', default=False, action='store_true', ...)
parser.add_argument('--classical', default=True, action='store_true', ...)
```

结果输出 ：
```
learning rate=0.0001
starting training process...
(step/total)=(  60/  60), batch accuracy = 10.20%.
starting evaluating process...
train set accuracy = 10.00%
test  set accuracy = 10.00%
train set loss     = 2.30258
test  set loss     = 2.30258
convergence factor = 0.00000
run epoch_step in 25.25 seconds
```

从step 1开始，所有结果都约为10%，我重复了多次，且尝试了不同的数据集，都得到了类似的结果。当将classical设置为False后，一切恢复正常，请问是什么问题呢？

**Comment by YemingMeng** [comment]
This resulting output is not a bug, but rather an anticipated result.

When the parameter --classical truned on, ResMPS fallback to a regular MPS, necessitating the use of two channels for classification tasks. Conversely, ResMPS, with the incorporation of residual connections, achieves comparable results with only one channel.

The default feature map in this project is set as $f(x) = x$, representing a single channel. To solve the issue, it is necessary to manually set the feature map to a double channel fashion, such as $f(x) = (x, 1-x)$.

To achieve this, you can execute the following command in the command line:

```python
python main.py --device cuda --dataset fashion_mnist --classical --feature_map "(lambda x:x, lambda x:1-x)"
```

---

这是预料之中的结果，而并非程序的Bug。

当设置参数--classical时，ResMPS会退化为传统的MPS模型。而传统的MPS模型需要两个channe来实现分类任务，ResMPS由于引入了residual connection只需要一个channel就可以相同的效果。

程序默认的特征映射(feature map)被设置为单通道的$f(x)=x$，因此在设置参数--classical之后需要将特征映射设置成双通道版本，例如$f(x)=(x, 1-x)$就可以得到预期的效果。

你可以通过在命令行执行如下命令来快速实现这一点

```python
python main.py --device cuda --dataset fashion_mnist --classical --feature_map "(lambda x:x, lambda x:1-x)"
```

**Comment by glin2022** [comment]
程序正常运行了。

十分感谢！

**Comment by YemingMeng** [comment]
不客气！

下周我将会做一个关于ResMPS的线上报告。如果你感兴趣，可以给我的邮箱发一个邮件，
yemingmeng@gmail.com
我会将报告的链接分享给你。
